Add verbosity levels 0-2.

diff --git a/mlbam/spider b/mlbam/spider
--- a/mlbam/spider
+++ b/mlbam/spider
@@ -21,7 +21,7 @@ usage() {
   echo "  -y <year>    Year for which to download files (default: $(date +%Y))."
   echo "  -l <league>  League: mlb, milb, etc (default: mlb)."
   echo "  -t           Include today's files (othewise stops at yesterday)."
-  echo "  -v           Be verbose (display downloaded files)."
+  echo "  -v <level>   Verbosity: 0 = silent, 1 = errors, 2 = files/warnings."
   echo "  -w           Overwrite existing files."
   echo "  -h           Print this help."
 }
@@ -46,7 +46,9 @@ gameids() {
   html=$(curl -sf "$(dateurl $1)/")
   curlexit="$?"
   if [ $curlexit -gt 0 ]; then
-    echo "Error: couldn't download $1 (curl exited with code $curlexit)" >&2
+    if [ $verbose -ge 1 ]; then
+      echo "Error: couldn't download $1 (curl exited with code $curlexit)" >&2
+    fi
     return 1
   fi
   sed -n 's:.*href="\(gid_[^/"]*\)/".*:\1:p' <<<"$html"
@@ -63,16 +65,20 @@ datafiles() {
 
 # download a file (takes URL and filesystem path)
 fetchfile() {
-  [ $verbose ] && echo "  $file"
+  if [ $verbose -ge 2 ]; then
+    echo "  $file"
+  fi
   curl -sf "$1" -o "$2.orig"
   curlexit="$?"
   if [ $curlexit -eq 22 ]; then
-    # warning when file doesn't appear to exist
-    echo "Warning: couldn't download $1 (server responded with HTTP >=400)"
+    if [ $verbose -ge 2 ]; then
+      echo "Warning: couldn't download $1 (server responded with HTTP >=400)"
+    fi
     return
   elif [ $curlexit -gt 0 ]; then
-    # error when problem connecting to server
-    echo "Error: couldn't download $1 (curl exited with code $curlexit)" >&2
+    if [ $verbose -ge 1 ]; then
+      echo "Error: couldn't download $1 (curl exited with code $curlexit)" >&2
+    fi
     return 1
   fi
 
@@ -84,7 +90,9 @@ fetchfile() {
   if [ $? -eq 0 ]; then
     rm "$2.orig"
   else
-    echo "Error: unexpected xmllint output for $2" >&2
+    if [ $verbose -ge 1 ]; then
+      echo "Error: unexpected xmllint output for $2" >&2
+    fi
   fi
 
   ((downloads += 1))
@@ -96,18 +104,18 @@ league=mlb
 previous=
 overwrite=
 today=
-verbose=
+verbose=1
 
 # keep track of downloads so we can sleep occasionally
 downloads=0
 
-while getopts "y:l:p:vwth" opt; do
+while getopts "y:l:p:v:wth" opt; do
   case $opt in
     y) year="$OPTARG" ;;
     l) league="$OPTARG" ;;
     p) previous="$OPTARG" ;;
     t) today=true ;;
-    v) verbose=true ;;
+    v) verbose="$OPTARG" ;;
     w) overwrite=true ;;
     h) usage; exit 0 ;;
     *) usage; exit 1 ;;
@@ -133,17 +141,17 @@ else
   firstdate=$(date -d "$year-02-01" +%s)
 fi
 
-echo "Downloading data for $league ($(formatdate "$firstdate" "%b %d") - \
+if [ $verbose -ge 1 ]; then
+  echo "Downloading data for $league ($(formatdate "$firstdate" "%b %d") - \
 $(formatdate "$lastdate" "%b %d"), $year) to $outputdir"
+fi
 
 starttime=$(date +%s)
-echo "Starting at $(date)"
-
 d="$firstdate"
 
 while true; do
   for gid in $(gameids $d); do
-    [ $verbose ] && echo "Processing game $gid"
+    [ $verbose -ge 1 ] && echo "Processing game $gid"
     gameurl="$(dateurl $d)/$gid"
     gamedir="$outputdir/$(datepath $d)/$gid"
     mkdir -p "$gamedir"
@@ -161,4 +169,6 @@ while true; do
 done
 
 elapsed=$(($(date +%s) - $starttime))
-echo "Finished in $(formatdate "$elapsed" "%H hrs %M mins %S secs")."
+if [ $verbose -ge 1 ]; then
+  echo "Finished in $(formatdate "$elapsed" "%H hrs %M mins %S secs")."
+fi
