Check that input file exists.

diff --git a/mlbam/xml_diff b/mlbam/xml_diff
--- a/mlbam/xml_diff
+++ b/mlbam/xml_diff
@@ -8,6 +8,11 @@ commit="$1"
 filepath="$2"
 tmpdir="tmp$RANDOM"
 
+if [ ! -e "$filepath" ]; then
+  echo "File not found."
+  exit 1
+fi
+
 mkdir "$tmpdir"
 
 git co $commit^ "$filepath"
